-- ============================================================
-- InvenTrack - Sistema de gestion de inventarios (PostgreSQL)
-- Sin CREATE DATABASE: ejecutar sobre la base ya creada
-- (pgAdmin local o la base que entrega Render).
-- IDs autogenerados con IDENTITY. Tras el esquema van los INSERT.
-- ============================================================

CREATE TABLE Categorias
(
  IDcategorias INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre       VARCHAR(200) NOT NULL,
  Descripcion  VARCHAR(100) NULL,
  PRIMARY KEY (IDcategorias)
);

CREATE TABLE Marcas
(
  IDmarca     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre      VARCHAR(100) NOT NULL,
  Descripcion VARCHAR(200) NULL,
  Activo      BOOL         NOT NULL,
  PRIMARY KEY (IDmarca)
);

CREATE TABLE Sucursales
(
  IDSucursal INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre     VARCHAR(100) NOT NULL,
  Direccion  VARCHAR(200) NULL,
  Telefono   VARCHAR(50)  NULL,
  Activo     BOOL         NOT NULL,
  PRIMARY KEY (IDSucursal)
);

CREATE TABLE Usuario
(
  IDusuario     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursal    INT          NOT NULL,
  Nombre        VARCHAR(200) NOT NULL,
  Correo        VARCHAR(100) NOT NULL,
  Contrasena    VARCHAR(200) NOT NULL,
  Rol           VARCHAR(20)  NOT NULL,
  Acceso        TIMESTAMP    NULL,
  Activo        BOOL         NOT NULL,
  FechaCreacion TIMESTAMP    NOT NULL,
  PRIMARY KEY (IDusuario)
);

CREATE TABLE Producto
(
  IDproducto    INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcategorias  INT           NOT NULL,
  IDmarca       INT           NULL,
  Codigo        VARCHAR(50)   NOT NULL,
  Nombre        VARCHAR(300)  NOT NULL,
  Descripcion   VARCHAR(200)  NULL,
  PrecioVenta   DECIMAL(10,2) NOT NULL,
  PrecioCosto   DECIMAL(10,2) NULL,
  StockMinimo   INT           NOT NULL,
  Activo        BOOL          NOT NULL,
  FechaCreacion TIMESTAMP     NOT NULL,
  PRIMARY KEY (IDproducto)
);

CREATE TABLE Inventario
(
  IDinventario       INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursal         INT          NOT NULL,
  IDproducto         INT          NOT NULL,
  CantidadDisponible INT          NOT NULL,
  Ubicacion          VARCHAR(100) NULL,
  Actualizacion      TIMESTAMP    NULL,
  PRIMARY KEY (IDinventario)
);

CREATE TABLE Proveedores
(
  IDproveedor INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre      VARCHAR(200) NOT NULL,
  RFC_NIT     VARCHAR(50)  NOT NULL,
  Telefono    VARCHAR(50)  NULL,
  Correo      VARCHAR(100) NULL,
  Direccion   VARCHAR(200) NULL,
  Activo      BOOL         NOT NULL,
  PRIMARY KEY (IDproveedor)
);

CREATE TABLE Producto_proveedor
(
  IDproductoProveedor INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproducto          INT           NOT NULL,
  IDproveedor         INT           NOT NULL,
  CodigoProveedor     VARCHAR(100)  NULL,
  PrecioCompra        DECIMAL(10,2) NOT NULL,
  Activo              BOOL          NOT NULL,
  PRIMARY KEY (IDproductoProveedor)
);

CREATE TABLE Clientes
(
  IDcliente     INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre        VARCHAR(200) NOT NULL,
  Documento     VARCHAR(50)  NOT NULL,
  Telefono      VARCHAR(50)  NULL,
  Correo        VARCHAR(100) NULL,
  Direccion     VARCHAR(200) NULL,
  FechaRegistro TIMESTAMP    NOT NULL,
  PRIMARY KEY (IDcliente)
);

CREATE TABLE Metodos_pago
(
  IDmetodoPago INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  Nombre       VARCHAR(50)  NOT NULL,
  Descripcion  VARCHAR(150) NULL,
  Activo       BOOL         NOT NULL,
  PRIMARY KEY (IDmetodoPago)
);

CREATE TABLE Ordenes_compra
(
  IDcompra    INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproveedor INT           NOT NULL,
  IDSucursal  INT           NOT NULL,
  IDusuario   INT           NOT NULL,
  FechaCompra TIMESTAMP     NOT NULL,
  Total       DECIMAL(12,2) NOT NULL,
  Estado      VARCHAR(20)   NOT NULL,
  Observacion VARCHAR(300)  NULL,
  PRIMARY KEY (IDcompra)
);

CREATE TABLE Detalle_compra
(
  IDdetalleCompra INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcompra        INT           NOT NULL,
  IDproducto      INT           NOT NULL,
  Cantidad        INT           NOT NULL,
  PrecioUnitario  DECIMAL(10,2) NOT NULL,
  Subtotal        DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (IDdetalleCompra)
);

CREATE TABLE Ventas
(
  IDventa      INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDcliente    INT           NOT NULL,
  IDSucursal   INT           NOT NULL,
  IDusuario    INT           NOT NULL,
  IDmetodoPago INT           NOT NULL,
  FechaVenta   TIMESTAMP     NOT NULL,
  Total        DECIMAL(12,2) NOT NULL,
  Estado       VARCHAR(20)   NOT NULL,
  Observacion  VARCHAR(300)  NULL,
  PRIMARY KEY (IDventa)
);

CREATE TABLE Detalle_ventas
(
  IDdetalleVenta INT           GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDventa        INT           NOT NULL,
  IDproducto     INT           NOT NULL,
  Cantidad       INT           NOT NULL,
  PrecioUnitario DECIMAL(10,2) NOT NULL,
  Descuento      DECIMAL(12,2) NOT NULL,
  Subtotal       DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (IDdetalleVenta)
);

CREATE TABLE Traslados
(
  IDtraslado        INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDSucursalOrigen  INT          NOT NULL,
  IDSucursalDestino INT          NOT NULL,
  IDusuario         INT          NOT NULL,
  FechaSolicitud    TIMESTAMP    NOT NULL,
  FechaEnvio        TIMESTAMP    NULL,
  FechaRecepcion    TIMESTAMP    NULL,
  Estado            VARCHAR(20)  NOT NULL,
  Observacion       VARCHAR(300) NULL,
  PRIMARY KEY (IDtraslado)
);

CREATE TABLE Detalle_traslado
(
  IDdetalleTraslado INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDtraslado        INT NOT NULL,
  IDproducto        INT NOT NULL,
  Cantidad          INT NOT NULL,
  PRIMARY KEY (IDdetalleTraslado)
);

CREATE TABLE Movimiento_inventario
(
  IDMovimiento      INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  IDproducto        INT          NOT NULL,
  IDusuario         INT          NOT NULL,
  IDSucursal        INT          NOT NULL,
  IDdetalleCompra   INT          NULL,
  IDdetalleVenta    INT          NULL,
  IDdetalleTraslado INT          NULL,
  TipoMovimiento    VARCHAR(20)  NOT NULL,
  Cantidad          INT          NOT NULL,
  Motivo            VARCHAR(100) NOT NULL,
  Fecha             TIMESTAMP    NOT NULL,
  PRIMARY KEY (IDMovimiento)
);

-- ------------------------------------------------------------
-- Llaves foraneas
-- ------------------------------------------------------------
ALTER TABLE Usuario
  ADD CONSTRAINT FK_Sucursales_TO_Usuario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Producto
  ADD CONSTRAINT FK_Categorias_TO_Producto
    FOREIGN KEY (IDcategorias) REFERENCES Categorias (IDcategorias);

ALTER TABLE Producto
  ADD CONSTRAINT FK_Marcas_TO_Producto
    FOREIGN KEY (IDmarca) REFERENCES Marcas (IDmarca);

ALTER TABLE Inventario
  ADD CONSTRAINT FK_Sucursales_TO_Inventario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Inventario
  ADD CONSTRAINT FK_Producto_TO_Inventario
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Producto_proveedor
  ADD CONSTRAINT FK_Producto_TO_Producto_proveedor
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Producto_proveedor
  ADD CONSTRAINT FK_Proveedores_TO_Producto_proveedor
    FOREIGN KEY (IDproveedor) REFERENCES Proveedores (IDproveedor);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Proveedores_TO_Ordenes_compra
    FOREIGN KEY (IDproveedor) REFERENCES Proveedores (IDproveedor);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Sucursales_TO_Ordenes_compra
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Ordenes_compra
  ADD CONSTRAINT FK_Usuario_TO_Ordenes_compra
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Detalle_compra
  ADD CONSTRAINT FK_Ordenes_compra_TO_Detalle_compra
    FOREIGN KEY (IDcompra) REFERENCES Ordenes_compra (IDcompra);

ALTER TABLE Detalle_compra
  ADD CONSTRAINT FK_Producto_TO_Detalle_compra
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Clientes_TO_Ventas
    FOREIGN KEY (IDcliente) REFERENCES Clientes (IDcliente);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Sucursales_TO_Ventas
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Usuario_TO_Ventas
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Ventas
  ADD CONSTRAINT FK_Metodos_pago_TO_Ventas
    FOREIGN KEY (IDmetodoPago) REFERENCES Metodos_pago (IDmetodoPago);

ALTER TABLE Detalle_ventas
  ADD CONSTRAINT FK_Ventas_TO_Detalle_ventas
    FOREIGN KEY (IDventa) REFERENCES Ventas (IDventa);

ALTER TABLE Detalle_ventas
  ADD CONSTRAINT FK_Producto_TO_Detalle_ventas
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_SucursalOrigen_TO_Traslados
    FOREIGN KEY (IDSucursalOrigen) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_SucursalDestino_TO_Traslados
    FOREIGN KEY (IDSucursalDestino) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Traslados
  ADD CONSTRAINT FK_Usuario_TO_Traslados
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Detalle_traslado
  ADD CONSTRAINT FK_Traslados_TO_Detalle_traslado
    FOREIGN KEY (IDtraslado) REFERENCES Traslados (IDtraslado);

ALTER TABLE Detalle_traslado
  ADD CONSTRAINT FK_Producto_TO_Detalle_traslado
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Producto_TO_Movimiento_inventario
    FOREIGN KEY (IDproducto) REFERENCES Producto (IDproducto);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Usuario_TO_Movimiento_inventario
    FOREIGN KEY (IDusuario) REFERENCES Usuario (IDusuario);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Sucursales_TO_Movimiento_inventario
    FOREIGN KEY (IDSucursal) REFERENCES Sucursales (IDSucursal);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_compra_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleCompra) REFERENCES Detalle_compra (IDdetalleCompra);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_ventas_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleVenta) REFERENCES Detalle_ventas (IDdetalleVenta);

ALTER TABLE Movimiento_inventario
  ADD CONSTRAINT FK_Detalle_traslado_TO_Movimiento_inventario
    FOREIGN KEY (IDdetalleTraslado) REFERENCES Detalle_traslado (IDdetalleTraslado);

-- ------------------------------------------------------------
-- Reglas de integridad (valores únicos y valores permitidos)
-- ------------------------------------------------------------
ALTER TABLE Usuario            ADD CONSTRAINT UQ_Usuario_Correo        UNIQUE (Correo);
ALTER TABLE Producto           ADD CONSTRAINT UQ_Producto_Codigo       UNIQUE (Codigo);
ALTER TABLE Inventario         ADD CONSTRAINT UQ_Inventario_Suc_Prod   UNIQUE (IDSucursal, IDproducto);
ALTER TABLE Producto_proveedor ADD CONSTRAINT UQ_ProdProv_Prod_Prov    UNIQUE (IDproducto, IDproveedor);
ALTER TABLE Proveedores        ADD CONSTRAINT UQ_Proveedores_RFC_NIT   UNIQUE (RFC_NIT);
ALTER TABLE Clientes           ADD CONSTRAINT UQ_Clientes_Documento    UNIQUE (Documento);
ALTER TABLE Categorias         ADD CONSTRAINT UQ_Categorias_Nombre     UNIQUE (Nombre);
ALTER TABLE Marcas             ADD CONSTRAINT UQ_Marcas_Nombre         UNIQUE (Nombre);

ALTER TABLE Usuario            ADD CONSTRAINT CK_Usuario_Rol           CHECK (Rol IN ('Administrador', 'Vendedor', 'Almacen'));
ALTER TABLE Producto           ADD CONSTRAINT CK_Producto_Precios      CHECK (PrecioVenta >= 0 AND (PrecioCosto IS NULL OR PrecioCosto >= 0) AND StockMinimo >= 0);
ALTER TABLE Inventario         ADD CONSTRAINT CK_Inventario_Cantidad   CHECK (CantidadDisponible >= 0);
ALTER TABLE Producto_proveedor ADD CONSTRAINT CK_ProdProv_Precio       CHECK (PrecioCompra >= 0);
ALTER TABLE Ordenes_compra     ADD CONSTRAINT CK_OrdenCompra_Estado    CHECK (Estado IN ('Pendiente', 'Recibida'));
ALTER TABLE Ordenes_compra     ADD CONSTRAINT CK_OrdenCompra_Total     CHECK (Total >= 0);
ALTER TABLE Detalle_compra     ADD CONSTRAINT CK_DetCompra_Valores     CHECK (Cantidad > 0 AND PrecioUnitario >= 0 AND Subtotal >= 0);
ALTER TABLE Ventas             ADD CONSTRAINT CK_Venta_Estado          CHECK (Estado IN ('Registrada', 'Anulada'));
ALTER TABLE Ventas             ADD CONSTRAINT CK_Venta_Total           CHECK (Total >= 0);
ALTER TABLE Detalle_ventas     ADD CONSTRAINT CK_DetVenta_Valores      CHECK (Cantidad > 0 AND PrecioUnitario >= 0 AND Descuento >= 0 AND Subtotal >= 0);
ALTER TABLE Traslados          ADD CONSTRAINT CK_Traslado_Estado       CHECK (Estado IN ('Pendiente', 'Enviado', 'Recibido'));
ALTER TABLE Traslados          ADD CONSTRAINT CK_Traslado_Sucursales   CHECK (IDSucursalOrigen <> IDSucursalDestino);
ALTER TABLE Detalle_traslado   ADD CONSTRAINT CK_DetTraslado_Cantidad  CHECK (Cantidad > 0);
ALTER TABLE Movimiento_inventario ADD CONSTRAINT CK_Movimiento_Tipo    CHECK (TipoMovimiento IN ('Entrada', 'Salida'));
ALTER TABLE Movimiento_inventario ADD CONSTRAINT CK_Movimiento_Cantidad CHECK (Cantidad > 0);

-- ============================================================
-- DATA DE PRUEBA (minimo 10 registros por tabla)
-- Los IDs no se insertan: los genera IDENTITY (1, 2, 3...) en el
-- orden de cada INSERT. Ejecutar sobre tablas recien creadas.
-- Contrasena de todos los usuarios de prueba: ClaveSegura2026* (BCrypt)
-- El stock de Inventario es coherente con Movimiento_inventario (incluido el stock inicial).
-- ============================================================

INSERT INTO Categorias (Nombre, Descripcion) VALUES
  ('Electronica',       'Equipos y accesorios electronicos'),
  ('Hogar',             'Articulos para el hogar'),
  ('Ferreteria',        'Herramientas y materiales'),
  ('Abarrotes',         'Alimentos y productos de consumo'),
  ('Utiles de oficina', 'Papeleria y utiles escolares'),
  ('Limpieza',          'Productos de limpieza del hogar'),
  ('Bebidas',           'Gaseosas, aguas y jugos'),
  ('Cuidado personal',  'Higiene y cuidado personal'),
  ('Automotriz',        'Accesorios y repuestos de auto'),
  ('Jugueteria',        'Juguetes y juegos');

INSERT INTO Marcas (Nombre, Descripcion, Activo) VALUES
  ('Samsung',       'Electronica de consumo',      TRUE),
  ('Philips',       'Iluminacion y audio',         TRUE),
  ('Truper',        'Herramientas manuales',       TRUE),
  ('Alicorp',       'Alimentos y consumo masivo',  TRUE),
  ('Faber-Castell', 'Utiles de escritura',         TRUE),
  ('Bosch',         'Herramientas electricas',     TRUE),
  ('Gloria',        'Lacteos y derivados',         TRUE),
  ('Oster',         'Electrodomesticos',           TRUE),
  ('Sapolio',       'Limpieza del hogar',          TRUE),
  ('Inca Kola',     'Bebidas gaseosas',            TRUE);

INSERT INTO Sucursales (Nombre, Direccion, Telefono, Activo) VALUES
  ('Sucursal Lima Centro', 'Av. Abancay 123, Lima',                '01-4231001', TRUE),
  ('Sucursal Miraflores',  'Av. Larco 456, Miraflores',            '01-4452002', TRUE),
  ('Sucursal Arequipa',    'Calle Mercaderes 789, Arequipa',       '054-203003', TRUE),
  ('Sucursal Surco',       'Av. Caminos del Inca 1200, Surco',     '01-4483004', TRUE),
  ('Sucursal San Isidro',  'Av. Republica de Panama 3500, San Isidro', '01-4224005', TRUE),
  ('Sucursal Trujillo',    'Jr. Pizarro 410, Trujillo',            '044-245006', TRUE),
  ('Sucursal Cusco',       'Av. El Sol 250, Cusco',                '084-236007', TRUE),
  ('Sucursal Piura',       'Av. Grau 640, Piura',                  '073-327008', TRUE),
  ('Sucursal Callao',      'Av. Sucre 880, Callao',                '01-4299009', TRUE),
  ('Sucursal Chiclayo',    'Calle San Jose 305, Chiclayo',         '074-231010', TRUE);

INSERT INTO Usuario (IDSucursal, Nombre, Correo, Contrasena, Rol, Acceso, Activo, FechaCreacion) VALUES
  (1, 'Carlos Admin',       'admin@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Administrador', NULL, TRUE, '2026-09-01 09:00:00'),
  (1, 'Lucia Vendedora',    'lucia@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Vendedor',      NULL, TRUE, '2026-09-01 09:10:00'),
  (2, 'Mario Vendedor',     'mario@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Vendedor',      NULL, TRUE, '2026-09-01 09:20:00'),
  (2, 'Rosa Almacenera',    'rosa@inventrack.pe',   '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Almacen',       NULL, TRUE, '2026-09-01 09:30:00'),
  (3, 'Jorge Vendedor',     'jorge@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Vendedor',      NULL, TRUE, '2026-09-01 09:40:00'),
  (3, 'Pedro Almacenero',   'pedro@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Almacen',       NULL, TRUE, '2026-09-01 09:50:00'),
  (4, 'Diana Almacenera',   'diana@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Almacen',       NULL, TRUE, '2026-09-01 10:00:00'),
  (5, 'Raul Almacenero',    'raul@inventrack.pe',   '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Almacen',       NULL, TRUE, '2026-09-01 10:10:00'),
  (5, 'Elena Vendedora',    'elena@inventrack.pe',  '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Vendedor',      NULL, TRUE, '2026-09-01 10:20:00'),
  (2, 'Hugo Administrador', 'hugo@inventrack.pe',   '$2a$10$/HnBiarFLqv3C.3WZ2MazexQYn5Ul4tWcF2s6cyE6ZfUq5HXqF.mS', 'Administrador', NULL, TRUE, '2026-09-01 10:30:00');

INSERT INTO Producto (IDcategorias, IDmarca, Codigo, Nombre, Descripcion, PrecioVenta, PrecioCosto, StockMinimo, Activo, FechaCreacion) VALUES
  (1, 1,  'ELEC-001', 'Televisor Samsung 43"',       'Smart TV 43 pulgadas',        1299.00, 950.00,  5, TRUE, '2026-09-02 10:00:00'),
  (2, 2,  'HOG-001',  'Foco LED Philips 12W',        'Luz blanca 12W',                12.50,   7.00, 50, TRUE, '2026-09-02 10:05:00'),
  (3, 3,  'FER-001',  'Taladro Truper 1/2"',         'Taladro percutor',             189.90, 130.00,  5, TRUE, '2026-09-02 10:10:00'),
  (4, 4,  'ABA-001',  'Aceite Primor 1L',            'Aceite vegetal botella 1L',      9.50,   7.20, 40, TRUE, '2026-09-02 10:15:00'),
  (5, 5,  'UTI-001',  'Lapices Faber-Castell x12',   'Caja de 12 lapices',            18.00,  11.00, 20, TRUE, '2026-09-02 10:20:00'),
  (1, 2,  'ELEC-002', 'Parlante Philips Bluetooth',  'Parlante portatil',            149.00,  95.00,  8, TRUE, '2026-09-02 10:25:00'),
  (3, 3,  'FER-002',  'Martillo Truper',             'Martillo de acero 16 oz',       35.00,  22.00, 10, TRUE, '2026-09-02 10:30:00'),
  (4, 4,  'ABA-002',  'Fideos Don Vittorio 500g',    'Fideos spaghetti 500g',          3.80,   2.60, 60, TRUE, '2026-09-02 10:35:00'),
  (5, 5,  'UTI-002',  'Cuaderno A4 cuadriculado',    'Cuaderno 100 hojas',             7.50,   4.20, 30, TRUE, '2026-09-02 10:40:00'),
  (2, 2,  'HOG-002',  'Enchufe inteligente Philips', 'Smart plug WiFi',               45.00,  28.00, 10, TRUE, '2026-09-02 10:45:00'),
  (6, 9,  'LIM-001',  'Limpiador Sapolio 1L',        'Limpiador multiuso 1L',          6.50,   4.00, 30, TRUE, '2026-09-02 10:50:00'),
  (7, 10, 'BEB-001',  'Gaseosa Inca Kola 1.5L',      'Gaseosa botella 1.5L',           7.50,   5.20, 40, TRUE, '2026-09-02 10:55:00'),
  (2, 8,  'HOG-003',  'Licuadora Oster 600W',        'Licuadora 600W vaso de vidrio', 189.00, 130.00,  6, TRUE, '2026-09-02 11:00:00'),
  (4, 7,  'ABA-003',  'Leche Gloria evaporada 400g', 'Leche evaporada entera 400g',    4.50,   3.40, 60, TRUE, '2026-09-02 11:05:00'),
  (3, 6,  'FER-003',  'Taladro Bosch 1/2"',          'Taladro percutor profesional',  259.00, 180.00,  5, TRUE, '2026-09-02 11:10:00');

-- Stock final por sucursal (coherente con las compras, ventas y traslados de abajo)
INSERT INTO Inventario (IDSucursal, IDproducto, CantidadDisponible, Ubicacion, Actualizacion) VALUES
  (1, 1,   8, 'Pasillo A-1', '2026-09-19 12:00:00'),
  (1, 6,   5, 'Pasillo A-2', '2026-09-19 12:00:00'),
  (1, 4,  20, 'Pasillo C-1', '2026-09-19 12:00:00'),
  (1, 8,  40, 'Pasillo C-2', '2026-09-19 12:00:00'),
  (2, 3,   8, 'Pasillo B-1', '2026-09-19 12:00:00'),
  (2, 7,  13, 'Pasillo B-2', '2026-09-19 12:00:00'),
  (2, 2,  36, 'Pasillo D-1', '2026-09-19 12:00:00'),
  (3, 5,  20, 'Pasillo E-1', '2026-09-19 12:00:00'),
  (3, 9,  40, 'Pasillo E-2', '2026-09-19 12:00:00'),
  (3, 10, 15, 'Pasillo D-2', '2026-09-19 12:00:00'),
  (1, 11, 56, 'Pasillo F-1', '2026-09-19 12:00:00'),
  (1, 12, 78, 'Pasillo F-2', '2026-09-19 12:00:00'),
  (2, 13,  9, 'Pasillo G-1', '2026-09-19 12:00:00'),
  (2, 14, 64, 'Pasillo G-2', '2026-09-19 12:00:00'),
  (3, 15,  9, 'Pasillo H-1', '2026-09-19 12:00:00'),
  (4, 1,   6, 'Pasillo A-1', '2026-09-19 12:00:00'),
  (4, 2,  45, 'Pasillo D-1', '2026-09-19 12:00:00'),
  (5, 4,  60, 'Pasillo C-1', '2026-09-19 12:00:00'),
  (3, 6,   2, 'Pasillo A-2', '2026-09-19 12:00:00'),
  (1, 3,   1, 'Pasillo B-1', '2026-09-19 12:00:00'),
  (5, 7,   4, 'Pasillo B-2', '2026-09-19 12:00:00'),
  (2, 8,  20, 'Pasillo C-2', '2026-09-19 12:00:00'),
  (2, 4,  10, 'Pasillo C-1', '2026-09-19 12:00:00');

INSERT INTO Proveedores (Nombre, RFC_NIT, Telefono, Correo, Direccion, Activo) VALUES
  ('Distribuidora Electro Peru SAC',  '20512345678', '01-6001001',  'ventas@electroperu.pe',   'Av. Industrial 100, Lima',     TRUE),
  ('Ferreteria Mayorista Truper',     '20587654321', '01-6002002',  'pedidos@truper.pe',       'Jr. Comercio 200, Lima',       TRUE),
  ('Alimentos y Consumo del Sur SAC', '20598765432', '054-607003',  'compras@consumosur.pe',   'Av. Parra 300, Arequipa',      TRUE),
  ('Limpieza Total SAC',              '20511122233', '01-6004004',  'ventas@limpiezatotal.pe', 'Av. Argentina 450, Callao',    TRUE),
  ('Bebidas del Peru SAC',            '20522233344', '01-6005005',  'pedidos@bebidasperu.pe',  'Av. Colonial 780, Lima',       TRUE),
  ('Bosch Herramientas Peru SAC',     '20533344455', '01-6006006',  'ventas@boschperu.pe',     'Av. Republica de Panama 900, Lima', TRUE),
  ('Lacteos Andinos SAC',             '20544455566', '054-608007',  'compras@lacteosandinos.pe','Av. Dolores 120, Arequipa',   TRUE),
  ('Electrohogar Oster Peru',         '20555566677', '01-6008008',  'ventas@osterperu.pe',     'Av. Javier Prado 2100, Lima',  TRUE),
  ('Importadora Norte SAC',           '20566677788', '044-609009',  'pedidos@importnorte.pe',  'Av. America 560, Trujillo',    TRUE),
  ('Mayorista Cusco EIRL',            '20577788899', '084-610010',  'ventas@mayoristacusco.pe','Av. La Cultura 310, Cusco',    TRUE);

INSERT INTO Producto_proveedor (IDproducto, IDproveedor, CodigoProveedor, PrecioCompra, Activo) VALUES
  (1,  1,  'EP-TV43',   950.00, TRUE),
  (6,  1,  'EP-PARL',    95.00, TRUE),
  (10, 1,  'EP-SPLUG',   28.00, TRUE),
  (3,  2,  'TR-TAL12',  130.00, TRUE),
  (7,  2,  'TR-MART',    22.00, TRUE),
  (4,  3,  'CS-ACE1',     7.20, TRUE),
  (8,  3,  'CS-FID5',     2.60, TRUE),
  (9,  3,  'CS-CUA4',     4.20, TRUE),
  (11, 4,  'LT-LIM1',     4.00, TRUE),
  (12, 5,  'BP-INCA15',   5.20, TRUE),
  (15, 6,  'BO-TAL12',  180.00, TRUE),
  (14, 7,  'LA-GLO400',   3.40, TRUE),
  (13, 8,  'OS-LIC600', 130.00, TRUE),
  (1,  9,  'IN-TV43',   955.00, TRUE),
  (4,  10, 'MC-ACE1',     7.30, TRUE);

INSERT INTO Clientes (Nombre, Documento, Telefono, Correo, Direccion, FechaRegistro) VALUES
  ('Ana Torres Quispe',        '45678912',    '987654321', 'ana.torres@correo.pe',         'Jr. Union 10, Lima',               '2026-09-03 11:00:00'),
  ('Bodega San Martin EIRL',   '20601234567', '986543210', 'bodega.sanmartin@correo.pe',   'Av. Brasil 55, Lima',              '2026-09-03 11:10:00'),
  ('Luis Paredes Rojas',       '41237856',    '985432109', 'luis.paredes@correo.pe',       'Calle Los Pinos 8, Miraflores',    '2026-09-03 11:20:00'),
  ('Marta Flores Huaman',      '47891234',    '984321098', 'marta.flores@correo.pe',       'Av. Ejercito 90, Arequipa',        '2026-09-03 11:30:00'),
  ('Cliente Mostrador',        '00000000',    NULL,        NULL,                           NULL,                               '2026-09-03 11:40:00'),
  ('Carmen Vega Salazar',      '40125678',    '983210987', 'carmen.vega@correo.pe',        'Av. Benavides 300, Surco',         '2026-09-04 09:00:00'),
  ('Ferreteria El Maestro SAC','20611223344', '982109876', 'elmaestro@correo.pe',          'Av. Universitaria 1500, Lima',     '2026-09-04 09:10:00'),
  ('Jorge Mendoza Ruiz',       '43219876',    '981098765', 'jorge.mendoza@correo.pe',      'Jr. Lampa 220, Lima',              '2026-09-04 09:20:00'),
  ('Minimarket Los Olivos SAC','20622334455', '980987654', 'losolivos@correo.pe',          'Av. Alfredo Mendiola 800, Los Olivos','2026-09-04 09:30:00'),
  ('Rosa Castillo Diaz',       '46789012',    '979876543', 'rosa.castillo@correo.pe',      'Calle Bolognesi 45, Arequipa',     '2026-09-04 09:40:00');

INSERT INTO Metodos_pago (Nombre, Descripcion, Activo) VALUES
  ('Efectivo',            'Pago en efectivo',                    TRUE),
  ('Tarjeta',             'Tarjeta de debito o credito',         TRUE),
  ('Yape',                'Pago con billetera digital',          TRUE),
  ('Transferencia',       'Transferencia bancaria',              TRUE),
  ('Plin',                'Pago con billetera digital Plin',     TRUE),
  ('Tarjeta de credito',  'Pago con tarjeta de credito',         TRUE),
  ('Tarjeta de debito',   'Pago con tarjeta de debito',          TRUE),
  ('Cheque',              'Pago con cheque de gerencia',         TRUE),
  ('Credito 30 dias',     'Venta al credito a 30 dias',          TRUE),
  ('Deposito en cuenta',  'Deposito directo en cuenta bancaria', TRUE);

INSERT INTO Ordenes_compra (IDproveedor, IDSucursal, IDusuario, FechaCompra, Total, Estado, Observacion) VALUES
  (1,  1, 1,  '2026-09-05 10:00:00', 10450.00, 'Recibida',  'Reposicion de electronica'),
  (2,  2, 4,  '2026-09-05 11:00:00',  1740.00, 'Recibida',  'Reposicion de ferreteria'),
  (3,  1, 1,  '2026-09-08 09:00:00',  1240.00, 'Pendiente', 'Pedido de abarrotes'),
  (4,  1, 1,  '2026-09-12 10:00:00',   240.00, 'Recibida',  'Reposicion de limpieza'),
  (5,  1, 1,  '2026-09-12 11:00:00',   416.00, 'Recibida',  'Reposicion de bebidas'),
  (6,  3, 6,  '2026-09-12 12:00:00',  1800.00, 'Recibida',  'Taladros para Arequipa'),
  (7,  1, 1,  '2026-09-14 09:00:00',   340.00, 'Pendiente', 'Pedido de leche'),
  (8,  2, 4,  '2026-09-12 13:00:00',  1300.00, 'Recibida',  'Licuadoras para Miraflores'),
  (9,  4, 7,  '2026-09-15 09:00:00',  4750.00, 'Pendiente', 'Televisores para Surco'),
  (10, 5, 8,  '2026-09-12 14:00:00',   432.00, 'Recibida',  'Aceite para San Isidro');

INSERT INTO Detalle_compra (IDcompra, IDproducto, Cantidad, PrecioUnitario, Subtotal) VALUES
  (1,  1,  10, 950.00, 9500.00),
  (1,  6,  10,  95.00,  950.00),
  (2,  3,  10, 130.00, 1300.00),
  (2,  7,  20,  22.00,  440.00),
  (3,  4, 100,   7.20,  720.00),
  (3,  8, 200,   2.60,  520.00),
  (4,  11, 60,   4.00,  240.00),
  (5,  12, 80,   5.20,  416.00),
  (6,  15, 10, 180.00, 1800.00),
  (7,  14,100,   3.40,  340.00),
  (8,  13, 10, 130.00, 1300.00),
  (9,  1,   5, 950.00, 4750.00),
  (10, 4,  60,   7.20,  432.00);

INSERT INTO Ventas (IDcliente, IDSucursal, IDusuario, IDmetodoPago, FechaVenta, Total, Estado, Observacion) VALUES
  (1,  1, 2, 1, '2026-09-09 15:00:00', 1597.00, 'Registrada', 'Venta de electronica'),
  (2,  2, 3, 3, '2026-09-09 16:00:00',  254.90, 'Registrada', 'Venta de ferreteria'),
  (3,  1, 2, 2, '2026-09-10 10:00:00',   85.50, 'Registrada', 'Venta de abarrotes'),
  (4,  3, 5, 1, '2026-09-10 11:00:00',   50.00, 'Registrada', 'Venta de utiles'),
  (6,  1, 2, 2, '2026-09-13 11:00:00',   41.00, 'Registrada', 'Venta de limpieza y bebidas'),
  (7,  2, 3, 1, '2026-09-13 12:00:00',  239.00, 'Registrada', 'Venta de hogar'),
  (8,  3, 5, 3, '2026-09-13 15:00:00',  250.00, 'Registrada', 'Venta de herramientas'),
  (9,  1, 2, 4, '2026-09-14 10:00:00', 1200.00, 'Registrada', 'Venta de televisor'),
  (10, 2, 3, 1, '2026-09-14 16:00:00',   62.00, 'Registrada', 'Venta de abarrotes y ferreteria'),
  (2,  1, 2, 2, '2026-09-15 11:00:00',  149.00, 'Registrada', 'Venta de parlante');

INSERT INTO Detalle_ventas (IDventa, IDproducto, Cantidad, PrecioUnitario, Descuento, Subtotal) VALUES
  (1,  1,  1, 1299.00,  0.00, 1299.00),
  (1,  6,  2,  149.00,  0.00,  298.00),
  (2,  3,  1,  189.90,  0.00,  189.90),
  (2,  7,  2,   35.00,  5.00,   65.00),
  (3,  4,  5,    9.50,  0.00,   47.50),
  (3,  8, 10,    3.80,  0.00,   38.00),
  (4,  5,  3,   18.00,  4.00,   50.00),
  (5,  11, 4,    6.50,  0.00,   26.00),
  (5,  12, 2,    7.50,  0.00,   15.00),
  (6,  13, 1,  189.00,  0.00,  189.00),
  (6,  2,  4,   12.50,  0.00,   50.00),
  (7,  15, 1,  259.00,  9.00,  250.00),
  (8,  1,  1, 1299.00, 99.00, 1200.00),
  (9,  14, 6,    4.50,  0.00,   27.00),
  (9,  7,  1,   35.00,  0.00,   35.00),
  (10, 6,  1,  149.00,  0.00,  149.00);

INSERT INTO Traslados (IDSucursalOrigen, IDSucursalDestino, IDusuario, FechaSolicitud, FechaEnvio, FechaRecepcion, Estado, Observacion) VALUES
  (1, 2, 1, '2026-09-11 09:00:00', NULL,                  NULL,                  'Pendiente', 'Traslado de televisores a Miraflores'),
  (1, 3, 1, '2026-09-11 10:00:00', '2026-09-11 15:00:00', '2026-09-12 16:00:00', 'Recibido',  'Parlantes para Arequipa'),
  (2, 1, 4, '2026-09-11 11:00:00', '2026-09-11 16:00:00', '2026-09-12 10:00:00', 'Recibido',  'Taladro para Lima Centro'),
  (3, 2, 6, '2026-09-16 09:00:00', '2026-09-16 14:00:00', NULL,                  'Enviado',   'Lapices para Miraflores'),
  (1, 4, 1, '2026-09-16 10:00:00', NULL,                  NULL,                  'Pendiente', 'Aceite y limpiador para Surco'),
  (2, 5, 4, '2026-09-12 09:00:00', '2026-09-12 14:00:00', '2026-09-13 11:00:00', 'Recibido',  'Martillos para San Isidro'),
  (3, 1, 6, '2026-09-17 09:00:00', NULL,                  NULL,                  'Pendiente', 'Cuadernos para Lima Centro'),
  (1, 2, 1, '2026-09-13 09:00:00', '2026-09-13 13:00:00', '2026-09-14 09:00:00', 'Recibido',  'Fideos y aceite para Miraflores'),
  (4, 1, 7, '2026-09-17 10:00:00', '2026-09-17 15:00:00', NULL,                  'Enviado',   'Focos de Surco a Lima Centro'),
  (5, 3, 8, '2026-09-18 09:00:00', NULL,                  NULL,                  'Pendiente', 'Aceite para Arequipa');

INSERT INTO Detalle_traslado (IDtraslado, IDproducto, Cantidad) VALUES
  (1,  1,  2),
  (2,  6,  2),
  (3,  3,  1),
  (4,  5,  5),
  (5,  4, 10),
  (6,  7,  4),
  (7,  9, 10),
  (8,  8, 20),
  (9,  2, 10),
  (10, 4,  5),
  (5,  11,15),
  (8,  4, 10);

-- Las primeras filas registran el stock inicial de cada sucursal, para que el kárdex cuadre con el inventario
INSERT INTO Movimiento_inventario (IDproducto, IDusuario, IDSucursal, IDdetalleCompra, IDdetalleVenta, IDdetalleTraslado, TipoMovimiento, Cantidad, Motivo, Fecha) VALUES
  (4 , 1, 1, NULL, NULL, NULL, 'Entrada', 30, 'Inventario inicial', '2026-09-01 08:00:00'),
  (8 , 1, 1, NULL, NULL, NULL, 'Entrada', 60, 'Inventario inicial', '2026-09-01 08:00:00'),
  (2 , 4, 2, NULL, NULL, NULL, 'Entrada', 40, 'Inventario inicial', '2026-09-01 08:00:00'),
  (14, 4, 2, NULL, NULL, NULL, 'Entrada', 70, 'Inventario inicial', '2026-09-01 08:00:00'),
  (5 , 6, 3, NULL, NULL, NULL, 'Entrada', 25, 'Inventario inicial', '2026-09-01 08:00:00'),
  (9 , 6, 3, NULL, NULL, NULL, 'Entrada', 40, 'Inventario inicial', '2026-09-01 08:00:00'),
  (10, 6, 3, NULL, NULL, NULL, 'Entrada', 15, 'Inventario inicial', '2026-09-01 08:00:00'),
  (1 , 7, 4, NULL, NULL, NULL, 'Entrada',  6, 'Inventario inicial', '2026-09-01 08:00:00'),
  (2 , 7, 4, NULL, NULL, NULL, 'Entrada', 55, 'Inventario inicial', '2026-09-01 08:00:00'),
  (1,  1, 1, 1,    NULL, NULL, 'Entrada', 10, 'Compra',   '2026-09-06 10:00:00'),
  (6,  1, 1, 2,    NULL, NULL, 'Entrada', 10, 'Compra',   '2026-09-06 10:00:00'),
  (3,  4, 2, 3,    NULL, NULL, 'Entrada', 10, 'Compra',   '2026-09-06 11:00:00'),
  (7,  4, 2, 4,    NULL, NULL, 'Entrada', 20, 'Compra',   '2026-09-06 11:00:00'),
  (1,  2, 1, NULL, 1,    NULL, 'Salida',   1, 'Venta',    '2026-09-09 15:00:00'),
  (6,  2, 1, NULL, 2,    NULL, 'Salida',   2, 'Venta',    '2026-09-09 15:00:00'),
  (3,  3, 2, NULL, 3,    NULL, 'Salida',   1, 'Venta',    '2026-09-09 16:00:00'),
  (7,  3, 2, NULL, 4,    NULL, 'Salida',   2, 'Venta',    '2026-09-09 16:00:00'),
  (11, 1, 1, 7,    NULL, NULL, 'Entrada', 60, 'Compra',   '2026-09-13 10:00:00'),
  (12, 1, 1, 8,    NULL, NULL, 'Entrada', 80, 'Compra',   '2026-09-13 10:30:00'),
  (15, 6, 3, 9,    NULL, NULL, 'Entrada', 10, 'Compra',   '2026-09-13 11:00:00'),
  (13, 4, 2, 11,   NULL, NULL, 'Entrada', 10, 'Compra',   '2026-09-13 11:30:00'),
  (4,  8, 5, 13,   NULL, NULL, 'Entrada', 60, 'Compra',   '2026-09-13 12:00:00'),
  (11, 2, 1, NULL, 8,    NULL, 'Salida',   4, 'Venta',    '2026-09-13 11:00:00'),
  (12, 2, 1, NULL, 9,    NULL, 'Salida',   2, 'Venta',    '2026-09-13 11:00:00'),
  (13, 3, 2, NULL, 10,   NULL, 'Salida',   1, 'Venta',    '2026-09-13 12:00:00'),
  (2,  3, 2, NULL, 11,   NULL, 'Salida',   4, 'Venta',    '2026-09-13 12:00:00'),
  (15, 5, 3, NULL, 12,   NULL, 'Salida',   1, 'Venta',    '2026-09-13 15:00:00'),
  (1,  2, 1, NULL, 13,   NULL, 'Salida',   1, 'Venta',    '2026-09-14 10:00:00'),
  (14, 3, 2, NULL, 14,   NULL, 'Salida',   6, 'Venta',    '2026-09-14 16:00:00'),
  (7,  3, 2, NULL, 15,   NULL, 'Salida',   1, 'Venta',    '2026-09-14 16:00:00'),
  (6,  2, 1, NULL, 16,   NULL, 'Salida',   1, 'Venta',    '2026-09-15 11:00:00'),
  (6,  1, 1, NULL, NULL, 2,    'Salida',   2, 'Traslado', '2026-09-11 15:00:00'),
  (6,  1, 3, NULL, NULL, 2,    'Entrada',  2, 'Traslado', '2026-09-12 16:00:00'),
  (3,  4, 2, NULL, NULL, 3,    'Salida',   1, 'Traslado', '2026-09-11 16:00:00'),
  (3,  4, 1, NULL, NULL, 3,    'Entrada',  1, 'Traslado', '2026-09-12 10:00:00'),
  (7,  4, 2, NULL, NULL, 6,    'Salida',   4, 'Traslado', '2026-09-12 14:00:00'),
  (7,  4, 5, NULL, NULL, 6,    'Entrada',  4, 'Traslado', '2026-09-13 11:00:00'),
  (8,  1, 1, NULL, NULL, 8,    'Salida',  20, 'Traslado', '2026-09-13 13:00:00'),
  (8,  1, 2, NULL, NULL, 8,    'Entrada', 20, 'Traslado', '2026-09-14 09:00:00'),
  (4,  1, 1, NULL, NULL, 12,   'Salida',  10, 'Traslado', '2026-09-13 13:00:00'),
  (4,  1, 2, NULL, NULL, 12,   'Entrada', 10, 'Traslado', '2026-09-14 09:00:00'),
  (5,  6, 3, NULL, NULL, 4,    'Salida',   5, 'Traslado', '2026-09-16 14:00:00'),
  (2,  7, 4, NULL, NULL, 9,    'Salida',  10, 'Traslado', '2026-09-17 15:00:00');
